version: "3.9"
services:
    chat-app-db:
        image: postgres:14.4
        restart: unless-stopped
        env_file:
            - ./chat-app-db/.env.local
        volumes:
            - database-data:/var/lib/postgresql/data
        ports:
            - "5433:5432"
        networks:
            - chat-app-net
    chat-app-auth:
        build:
            context: ./chat-app-auth
        restart: unless-stopped
        depends_on:
            - "chat-app-db"
        environment:
            DATABASE_URL: postgres://chatapp:chatapp@chat-app-db:5432/chatapp
        volumes:
            - ./chat-app-auth:/usr/src/app
            - /usr/src/app/node_modules
        ports:
            - "8085:8084"
        networks:
            - chat-app-net
    chat-app-graphql-engine:
        image: hasura/graphql-engine:v2.48.4-ce.cli-migrations-v3
        depends_on:
            - "chat-app-db"
            - "chat-app-auth"
        restart: unless-stopped
        env_file:
            - ./chat-app-graphql-engine/.env.development.local
        volumes:
            - ./chat-app-graphql-engine/migrations:/hasura-migrations
            - ./chat-app-graphql-engine/metadata:/hasura-metadata
        ports:
            - "8081:8080"
        networks:
            - chat-app-net
    chat-app-front:
        build:
            context: ./chat-app-front
        restart: unless-stopped
        depends_on:
            - "chat-app-graphql-engine"
        env_file:
            - ./chat-app-front/.env.development.local
        volumes:
            - ./chat-app-front:/usr/src/app
            - /usr/src/app/node_modules
        ports:
            - "81:3000"
        networks:
            - chat-app-net
volumes:
    database-data:
networks:
    chat-app-net:
        name: chat-app-net
