version: "3.9"
services:
    chat-app-db-test:
        image: postgres:17
        restart: unless-stopped
        environment:
            POSTGRES_USER: chatapp_test
            POSTGRES_PASSWORD: chatapp_test
            POSTGRES_DB: chatapp_test
        volumes:
            - chat-app-db-test-data:/var/lib/postgresql/data
            - ../chat-app-graphql-engine/seeds:/docker-entrypoint-initdb.d
        ports:
            - "5434:5432"
        networks:
            - chat-app-test-net
    chat-app-auth-test:
        build:
            context: ../chat-app-auth
        restart: unless-stopped
        depends_on:
            - "chat-app-db-test"
        environment:
            DATABASE_URL: postgres://chatapp_test:chatapp_test@chat-app-db-test:5432/chatapp_test
            SESSION_SECRET: test-secret-for-e2e-tests
            NODE_ENV: test
            PORT: 8084
        volumes:
            - ../chat-app-auth:/usr/src/app
            - /usr/src/app/node_modules
        ports:
            - "8086:8084"
        networks:
            - chat-app-test-net
    chat-app-graphql-engine-test:
        image: hasura/graphql-engine:v2.48.4-ce.cli-migrations-v3
        depends_on:
            - "chat-app-db-test"
            - "chat-app-auth-test"
        restart: unless-stopped
        environment:
            HASURA_GRAPHQL_DATABASE_URL: postgres://chatapp_test:chatapp_test@chat-app-db-test:5432/chatapp_test
            HASURA_GRAPHQL_ENABLE_CONSOLE: "false"
            HASURA_GRAPHQL_ADMIN_SECRET: test-admin-secret-e2e
            HASURA_GRAPHQL_UNAUTHORIZED_ROLE: anonymous
            HASURA_GRAPHQL_AUTH_HOOK: http://chat-app-auth-test:8084/auth/webhook
        volumes:
            - ../chat-app-graphql-engine/migrations:/hasura-migrations
            - ../chat-app-graphql-engine/metadata:/hasura-metadata
        ports:
            - "8082:8080"
        networks:
            - chat-app-test-net
    chat-app-front-test:
        build:
            context: .
        restart: unless-stopped
        depends_on:
            - "chat-app-graphql-engine-test"
        env_file:
            - ./.env.test.local
        volumes:
            - .:/usr/src/app
            - /usr/src/app/node_modules
        ports:
            - "82:3000"
        networks:
            - chat-app-test-net

volumes:
    chat-app-db-test-data:

networks:
    chat-app-test-net:
        name: chat-app-test-net